language: python
python: 3.8
env:
  - TOX_ENV=pep8
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=py36
  - TOX_ENV=py37
  - TOX_ENV=py38
install:
  - pip install tox coveralls
script:
  - tox -e $TOX_ENV
after_success:
  - coveralls -v
