language: python
python: 2.7
env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=pep8
  - TOX_ENV=pypy
install:
  - pip install tox coveralls
script:
  - tox -e $TOX_ENV
after_success:
  - coveralls -v
