language: python
python: 2.7
env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=pep8
  - TOX_ENV=pypy
  - TOX_ENV=cover
install:
  - pip install tox 
  - if [ "x$TOX_ENV" = 'xcover' ]; then pip install coveralls; fi
script:
  - tox -e $TOX_ENV
after_success:
  - if [ "x$TOX_ENV" = 'xcover' ]; then coveralls; fi
